 1  version: 0.2
 2
 3  env:
 4    variables:
 5      AWS_REGION: "us-east-1"
 6      ECR_REPO: "my-hf-model-ecr"
 7      S3_BUCKET: "648758970526-us-east-1-models"
 8      MODEL_TAR: "model.tar.gz"
 9      AWS_ACCOUNT_ID: "648758970526"
10
11  phases:
12    install:
13      commands:
14        - echo "Installing Python deps..."
15        - pip install --upgrade pip
16        - pip install boto3
17
18    pre_build:
19      commands:
20        - echo "Logging into ECR..."
21        - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
22        - echo "Checking ECR repo..."
23        - |
24          if ! aws ecr describe-repositories --repository-names $ECR_REPO --region $AWS_REGION >/dev/null 2>&1; then
25            aws ecr create-repository --repository-name $ECR_REPO --region $AWS_REGION
26          fi
27        - echo "Model tar already exists in S3 at s3://$S3_BUCKET/$MODEL_TAR"
28
29    build:
30      commands:
31        - echo "Building Docker image..."
32        - docker build -t $ECR_REPO .
33        - docker tag $ECR_REPO:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:latest
34
35    post_build:
36      commands:
37        - echo "Pushing Docker image to ECR..."
38        - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:latest
39        - echo "DONE: Docker image pushed to ECR successfully."
