version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running HF model download and S3 upload script...
      - python hf_to_s3.py

artifacts:
  files:
    - '**/*'
